codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: false

  ignore:
    - "src/test/**"
    - "src/main/resources/**"
    - "src/main/java/com/chang1o/recipe/Main.java"
    - "**/src/main/java/com/chang1o/ui/**"
    - "**/src/main/java/com/chang1o/session/**"
    - "**/src/main/java/com/chang1o/util/DBUtil.java"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "src/test/**"
  - "src/main/resources/**"
  - "src/main/java/com/chang1o/recipe/Main.java"
